## Numpy

In [1]:
pip install numpy


[notice] A new release of pip is available: 23.0 -> 23.1
[notice] To update, run: python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

### Numpy - 기초

In [17]:
arr1 = np.array([1.0, 2.0, 3]) # 1차원 배열

arr1
arr1.shape # (3,)

arr1.dtype

dtype('float64')

In [11]:
arr2 = np.array([[1,2,3], [1,2,3]]) # 2차원 배열

arr2
arr2.shape # (2,3) => 2행 3열인 2차원 배열이다.
arr2.ndim # 2 => 2차원

2

In [21]:
list3 = [ [ [1,2,3] ] ] # list

arr3 = np.array(list3) # nparray

arr3
arr3.ndim # 3 => 3차원
arr3.dtype
arr3.shape # (1,1,3)

# 컴퓨터는 => 0과 1만 이해할 수 있다. -> 나중에 데이터도 숫자형 데이터로 바꿔주셔야 합니다.

(1, 1, 3)

In [22]:
list2 = [1, 2, 'c']

arr4 = np.array(list2)
arr4

array(['1', '2', 'c'], dtype='<U21')

In [26]:
arr = np.array(["1", "2", "3", "4", "5"])
arr.dtype

# final_arr = arr.astype(np.int64)
# final_arr = arr.astype('int64')
final_arr = arr.astype('float')
final_arr.dtype

dtype('float64')

### ndarray
- arange
- zeros
- ones

In [31]:
# arange()
arr = np.arange(10)

# slicing
arr[0:6]

# indexing
arr[-1]

arr[arr > 5]

array([6, 7, 8, 9])

In [33]:
# zeors
arr = np.zeros((3,2), dtype='int32')

print(arr, arr.ndim, arr.dtype, arr.shape)

[[0 0]
 [0 0]
 [0 0]] 2 int32 (3, 2)


In [36]:
# ones
np.ones((10,10), dtype='int')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### reshape() - 차원과 크기 변경

In [44]:
arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(2,5) # 2행 5열
print(arr2)

arr3 = arr1.reshape(5,2) # 5행 2열
print(arr3)

# cannot reshape array of size 10 into shape (3,4)
# arr4 = arr1.reshape(3,4) # 3행 4열 => 12개
# arr4

arr2 = arr1.reshape(-1,) # 2행 5열
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [46]:
arr = np.arange(8)
arr

arr2 = arr.reshape(-1,4)
arr2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5) # 5열에 맞춰서 -> 행을 만들어줘 (알아서)
print(array2)
print(array2.shape)

array3 = array1.reshape(5, -1) # 5행에 맞춰서 -> 열을 만들어줘
print(array3)
print(array3.shape)

array4 = array1.reshape(2, -1) # 2행에 맞춰서 -> 열을 만들어줘
array4

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 인덱싱, 슬라이싱

In [48]:
arr = np.arange(1,10)

arr[0]
arr[0:5]
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr = np.arange(1,10)

arr2 = arr.reshape(3,3)
print(arr2)

arr2[1, 1] # 5
arr2[2,2] # 9

# arr2[0, 0:3] # [1,2,3]
arr2[1, 0:3] # [4,5,6]

# [3,6,9]
arr2[:, 2]

# [[1]
#  [4]]

arr3 = arr2[:2, :1]
arr3

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1],
       [4]])

- boolean indexing

In [72]:
arr = np.arange(1, 10)
arr[arr > 5]

array([6, 7, 8, 9])

### sort()
- 정렬

In [76]:
arr = np.array([10, 30, 5, 1, 100])

# 오름차순
arr_sorted = np.sort(arr)
arr_sorted

# 내림차순
arr_sorted[::-1]

array([100,  30,  10,   5,   1])

In [77]:
arr_countries = np.array(["kor", "usa", "china"])

arr_sorted = np.sort(arr_countries)
arr_sorted

array(['china', 'kor', 'usa'], dtype='<U5')

### 행렬의 연산

In [82]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

print(arr1)
print(arr2)

arr_add = np.add(arr1, arr2)
arr_add

arr_mul = np.multiply(arr1, arr2) # 단순 곱셈한 값
print(arr_mul)

arr_dot = np.dot(arr1, arr2)
print(arr_dot)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [88]:
# Q1. 2차원 배열에서 행렬의 각 행의 평균을 계산하는 코드를 작성하세요.

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
# axis=0(행), axis=1 (열), axis=2 (채널)
row_means = np.mean(arr, axis=0)
row_means = np.mean(arr, axis=1)
row_means

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [93]:
# Q2. 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성하세요.
# 짝수값을 출력을 한다. / 해당 값들의 인덱스 값을 가져온다.

arr = np.array([1, 2, 3, 4, 5, 6])

even_indexes = np.arange(0, arr.size, 2)
even_indexes

arr[even_indexes]


array([1, 3, 5])

In [96]:
# Q3. 2차원 배열의 주 대각선 상에 있는 원소들을 출력하는 코드를 작성하세요.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

print(np.diag(arr)) # diag: diagonal 줄임말

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [108]:
# Q4. 2차원 배열 표준 편차를 계산하는 코드를 작성하세요.
# 표준 편차 => np.std()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr.shape)

np.std(arr) # 전체 표준편차
np.std(arr, axis=0) # 행의 표준편차
np.std(arr, axis=1) # 열의 표준편차

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


array([0.81649658, 0.81649658, 0.81649658])

In [ ]:
# Q5. 1차원 배열에서 원소들의 순위를 계산하는 코드를 작성하세요.
# - argsort()

import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
# 1차원 배열 arr을 생성하고, 값을 지정합니다.

ranks = np.argsort(np.argsort(-arr))
# np.argsort() 함수를 사용하여, 배열의 값들을 오름차순으로 정렬했을 때의 인덱스를 반환합니다. 
# 이후에 - 연산자를 사용하여 내림차순으로 정렬했을 때의 인덱스를 구합니다. 
# 마지막으로 다시 np.argsort() 함수를 사용하여 내림차순으로 정렬된 인덱스를 오름차순으로 정렬하여, 각 원소들의 순위를 계산합니다.




ranks

array([4, 6, 3, 7, 2, 0, 5, 1])

In [11]:
# Q6. 2차원 배열에서 각 행의 최대값과 그 인덱스를 출력하는 코드를 작성하세요.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

row_max = np.amax(arr, axis=1)
row_max

row_argmax = np.argmax(arr, axis=1)
row_argmax

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 2, 2])

In [13]:
# Q7. 1차원 배열에서 중앙값을 계산하는 코드를 작성하세요.
# - median()
arr = np.array([1, 2, 3, 4, 5])

median = np.median(arr)
median

3.0

In [15]:
# 2차원 배열에서 각 열의 최소값과 그 인덱스를 출력하는 코드를 작성하세요.

arr = np.array([[1, 2, 3], [4, 1, 6], [7, 8, 2]])
print(arr)

col_min = np.amin(arr, axis=0)
col_min

[[1 2 3]
 [4 1 6]
 [7 8 2]]


array([1, 1, 2])

In [20]:
# Q8. 1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성하세요.

arr = np.array([1, 4, 6, 3, 9, 2, 7, 8])
print(arr)

arr[arr >= 5]

[1 4 6 3 9 2 7 8]


array([6, 9, 7, 8])

In [22]:
# Q9. 2차원 배열에서 모든 원소의 값을 2배로 만드는 코드를 작성하세요.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_arr = arr * 2

print(new_arr)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [26]:
# Q10. 1차원 배열에서 원소의 값이 3 또는 5인 것들의 인덱스를 출력하는 코드를 작성하세요.

arr = np.array([1, 3, 5, 2, 4, 6, 3, 5, 7])
print(arr)

# 조건: 원소의 값이 3 또는 5인 것 + 해당 값의 인덱스를 출력

np.where((arr==3) | (arr==5))

np.where?

[1 3 5 2 4 6 3 5 7]


Docstring:
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Example

In [30]:
# Q11. 2차원 배열에서 행렬의 각 열의 값을 오름차순으로 정렬하는 코드를 작성하세요.

arr = np.array([[3, 2, 1], [6, 5, 4], [9, 8, 7]]) # 3x3, 2차원 행렬

print(arr)

new_arr1 = np.sort(arr, axis=0)
print(new_arr1)

new_arr2 = np.sort(arr, axis=1) # 행을 기준으로 오름차순 정렬
print(new_arr2)

np.sort?

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Signature: np.sort(a, axis=-1, kind=None, order=None)
Docstring:
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecif

In [33]:
# Q12. 1차원 배열에서 중복되는 값을 제거하는 코드를 작성하세요.

arr = np.array([1, 2, 3, 2, 4, 3, 5])

np.s(arr)

array([1, 2, 3, 4, 5])